export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAAUTHENTICATED = 'SET_UNAAUTHENTICATED';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';
export const CLEAR_UI = 'CLEAR_UI';
export const SET_USUARIO = 'SET_USUARIO';
